### ISSUE TITLE
[Suggestion] Add an extra mechanic that should increases/decreases the temperature

### ISSUE THREAD

**Issue by TheTrueSCP** [TeamMoegMC/FrostedHeart#25]
Since this modpack is similar to Frostpunk(at least i think so), I would suggest adding the "getting colder" mechanic. This mechanic shoud randomly increases or decreases the temperature every few days. So it would be even harder to survive in mid- and lategame. However, this mechanic should also be able to be switched on and off via the configuration.

**Comment by yuesha-yc** [comment]
This is implemented in 0.5 by our dynamic climate system. You will encounter random cold wave and warm periods and adjust your survival strategy by using forecast system.

**Comment by TheTrueSCP** [comment]
oh, ok nice
