### ISSUE TITLE
Immersive Engineering own Multiblocks cant be formed with the Engineer's Hammer

### ISSUE THREAD

**Issue by TheTrueSCP** [TeamMoegMC/FrostedHeart#26]
When i try to form a multiblock structure from Immersive Engineering, these cant be formed, but the multiblocks from FrostedHeart can be formed.
As example: if i want to form the saw mill and right-click the multiblock on the correct block, the player plays the interaction animation, but the structure doesnt form.
But when i try to form the Crucible or Steam Turbine, it works without any problems

**Comment by khjxiaogu** [comment]
This is intended, We locked uncraftable multiblocks by now.
