### ISSUE TITLE
Crops cannot be placed

### ISSUE THREAD

**Issue by TheTrueSCP** [TeamMoegMC/FrostedHeart#27]
When i try to place a crop, the game say the temperature is to low, but its not. (look at screenshot for more details). Even after the message that the crop wasnt growing, it still disappears from the inventory, but if i click on the slot where the crop was, the crop appears again

![2023-01-09_13 58 03](https://user-images.githubusercontent.com/92249648/211315332-0670166d-977d-4c5d-a130-7008f2af587b.png)

**Comment by khjxiaogu** [comment]
Please read the quest book more carefully at quest: [Temperature](http://wiki.teammoeg.com/index.php?title=TWR_Quest-Temperature) and notice that temperature needed to plant a plant is different from temperature you see on the orb :D
