### ISSUE TITLE
Not compatible with SpongeForge

### ISSUE THREAD

**Issue by drag0n1zed** [TeamMoegMC/FrostedHeart#33]
When the mod is run with spongeforge 1.16.5-36.2.5-8.1.0-RC1312, the server crashes when loading.
模组与SpongeForge 版本1.16.5-36.2.5-8.1.0-RC1312运行时服务器会crash掉
Logs: https://gist.github.com/SyuKoshiishi/65e4a4fcb5ba51c1e9be00aab4ed6e37

**Comment by SyuKoshiishi** [comment]
SpongeForge那边的issue: https://github.com/SpongePowered/Sponge/issues/3846
